meta_product_name: "Decide.it"
meta_title: "Decide.it"
meta_description: "Efficient decision making, prepare your projects for success"
meta_image: "meta-image.png"
twitter_account: "@product_twitter_account"   # required for Twitter Cards
